name: E2E

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
    

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: [openai, gemini]
    env:
      ANTHROPIC_BASE_URL: http://localhost:8082
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Claude Code CLI
        run: npm install -g @anthropic-ai/claude-code

      - name: Prepare provider env
        run: |
          if [ "${{ matrix.provider }}" = "openai" ]; then
            echo "PREFERRED_PROVIDER=openai" >> $GITHUB_ENV
          else
            echo "PREFERRED_PROVIDER=google" >> $GITHUB_ENV
          fi

      - name: Start proxy in background
        run: |
          nohup uvx --from=. claude-code-proxy > server.log 2>&1 &
          sleep 5

      - name: CLI basic test
        run: |
          if [ "${{ matrix.provider }}" = "openai" ]; then
            ANTHROPIC_BASE_URL=http://localhost:8082 claude --version
            ANTHROPIC_BASE_URL=http://localhost:8082 claude "What's 2+2?"
          else
            ANTHROPIC_BASE_URL=http://localhost:8082 claude --version
            ANTHROPIC_BASE_URL=http://localhost:8082 claude "What's the capital of France?"
          fi

      - name: Stop proxy
        run: pkill -f claude-code-proxy || true
